name: Python CI

on:
  push:
    branches:
      - master  # Или ваша основная ветка
  pull_request:
    branches:
      - master  # Или ваша основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Укажите ваш файл зависимостей

    - name: Install Chrome and Firefox
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update && sudo apt-get install google-chrome-stable -y
        sudo apt-get install firefox -y

    - name: Run all tests
      run: |
        # Запуск тестов в Chrome
        python -m pytest --driver Chrome
