name: Тестирование веб-приложения

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка зависимостей
      run: npm install

    - name: Запуск тестов
      run: npm test