name: Python CI

on:
  push:
    branches:
      - master  # Или ваша основная ветка
  pull_request:
    branches:
      - master  # Или ваша основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Укажите ваш файл зависимостей

    - name: Run a single test
      run: python -m pytest /github/workspace/qatest/tests/task_test.py::test_name

